# Generated by Django 6.0.4 on 2026-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncuser',
            name='macc_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='syncuser',
            name='pass_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='syncuser',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
