# Generated by Django 6.0.4 on 2026-05-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_syncuser_macc_id_alter_syncuser_pass_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('accno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('customer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('particulars', models.CharField(blank=True, max_length=250, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('voucher_no', models.BigIntegerField(blank=True, null=True)),
                ('narration', models.CharField(blank=True, max_length=250, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acc_ledgers',
                'ordering': ['code', 'date', 'accno'],
            },
        ),
    ]
