# Generated by Django 6.0.4 on 2026-05-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='settings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
